import type { SanityImageSource } from '@sanity/image-url';
import type { CmsImage } from '../content/types';
import { urlFor } from '../sanity/image';

/**
 * The Open Graph/Twitter Card sharing image builder. Kept out of `seo.ts`
 * because it needs `urlFor` from `src/sanity/image.ts`, which throws at
 * import time when the Sanity project id/dataset env vars are missing;
 * `seo.ts` stays free of that dependency so its tests never need them.
 */

export interface ShareImage {
  url: string;
  width: number;
  height: number;
  /** Omitted when the alt text passed in is empty or whitespace-only. */
  alt?: string;
}

const SHARE_IMAGE_WIDTH = 1200;
const SHARE_IMAGE_HEIGHT = 630;
const FALLBACK_IMAGE_PATH = '/og-fallback.png';

/**
 * Builds the 1200x630 Open Graph/Twitter Card sharing image. A Sanity-backed
 * hero (`source` present) gets an editor-controlled, hotspot-aware,
 * forced-JPEG crop (see the `format('jpg')` note below). Without one — the
 * repository fallback content, `src/data/placeholders.ts` — the static
 * brand card at `public/og-fallback.png` (generated by
 * `scripts/generate-share-fallback.ts`; see that script for what it is and
 * why) is used instead, but only once `siteUrl` is known: Open Graph images
 * must be absolute, and a relative path is the only thing this project
 * could otherwise offer. `siteUrl` is the already-resolved `URL` (see
 * `resolveSiteUrl` in `seo.ts`), passed in rather than re-parsed here, so
 * this file never has to import from `seo.ts`. `fallbackAlt` is likewise
 * passed in (from `site.ts` via `Seo.astro`) rather than imported, keeping
 * this module free of any site-copy dependency.
 */
export function resolveShareImage(
  image: CmsImage | undefined,
  siteUrl: URL | undefined,
  fallbackAlt: string,
): ShareImage | undefined {
  if (image?.source) {
    return buildSanityShareImage(image.source, image.alt);
  }
  if (!siteUrl) return undefined;

  return withOptionalAlt(
    {
      url: new URL(FALLBACK_IMAGE_PATH, siteUrl).toString(),
      width: SHARE_IMAGE_WIDTH,
      height: SHARE_IMAGE_HEIGHT,
    },
    fallbackAlt,
  );
}

/**
 * `format('jpg')` (`fm=jpg`) is forced here, unlike the `auto('format')`
 * used for on-page `<img>` srcsets in `sanity-image.ts`: a real browser
 * negotiates its own `Accept` header correctly, but link-preview fetchers
 * (Facebook, Twitter/X, LinkedIn, WhatsApp, Slack) fetch the image once,
 * often without an `Accept` header that reliably advertises AVIF/WebP
 * support, so `auto=format` risks a format some unfurlers cannot render.
 * JPEG is universally supported for link previews.
 */
function buildSanityShareImage(source: SanityImageSource, alt: string): ShareImage {
  const url = urlFor(source)
    .width(SHARE_IMAGE_WIDTH)
    .height(SHARE_IMAGE_HEIGHT)
    .fit('crop')
    .format('jpg')
    .url();

  return withOptionalAlt({ url, width: SHARE_IMAGE_WIDTH, height: SHARE_IMAGE_HEIGHT }, alt);
}

/** Trims `alt` and omits it entirely rather than keeping an empty/whitespace value. */
function withOptionalAlt(image: Omit<ShareImage, 'alt'>, alt: string): ShareImage {
  const trimmed = alt.trim();
  return trimmed ? { ...image, alt: trimmed } : image;
}
