/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ServiceCategory = {
  _id: string;
  _type: "serviceCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  image: ImageWithAlt;
  visible?: boolean;
  orderRank?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ServiceCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "serviceCategory";
};

export type PortfolioImage = {
  _id: string;
  _type: "portfolioImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: ImageWithAlt;
  caption?: string;
  categories?: Array<
    {
      _key: string;
    } & ServiceCategoryReference
  >;
  visible?: boolean;
  orderRank?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    image: ImageWithAlt;
    mobileImage?: ImageWithAlt;
  };
  biography?: {
    portrait: ImageWithAlt;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cta?: CallToAction;
  };
};

export type CallToAction = {
  _type: "callToAction";
  label?: string;
  target?: "whatsapp" | "contact" | "url";
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ServiceCategory
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | ServiceCategoryReference
  | PortfolioImage
  | HomePage
  | CallToAction
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{      image{  asset->{    _id,    url,    metadata{      lqip,      dimensions{        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},      mobileImage{  asset->{    _id,    url,    metadata{      lqip,      dimensions{        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop}    },    biography{      portrait{  asset->{    _id,    url,    metadata{      lqip,      dimensions{        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},      body,      cta{        label,        target,        url      }    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      biography: null;
    }
  | {
      hero: {
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        };
        mobileImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
      } | null;
      biography: {
        portrait: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        };
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: null;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cta: {
          label: string | null;
          target: "contact" | "url" | "whatsapp" | null;
          url: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/queries.ts
// Variable: PORTFOLIO_IMAGES_QUERY
// Query: *[_type == "portfolioImage" && visible == true] | order(orderRank asc){    _id,    image{  asset->{    _id,    url,    metadata{      lqip,      dimensions{        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},    caption,    "categories": categories[]->{      _id,      title,      "slug": slug.current    }  }
export type PORTFOLIO_IMAGES_QUERY_RESULT = Array<{
  _id: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  caption: string | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: SERVICE_CATEGORIES_QUERY
// Query: *[_type == "serviceCategory" && visible == true] | order(orderRank asc){    _id,    title,    "slug": slug.current,    image{  asset->{    _id,    url,    metadata{      lqip,      dimensions{        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop}  }
export type SERVICE_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "homePage"][0]{\n    hero{\n      image{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n      mobileImage{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n}\n    },\n    biography{\n      portrait{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n      body,\n      cta{\n        label,\n        target,\n        url\n      }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "portfolioImage" && visible == true] | order(orderRank asc){\n    _id,\n    image{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n    caption,\n    "categories": categories[]->{\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n': PORTFOLIO_IMAGES_QUERY_RESULT;
    '\n  *[_type == "serviceCategory" && visible == true] | order(orderRank asc){\n    _id,\n    title,\n    "slug": slug.current,\n    image{\n  asset->{\n    _id,\n    url,\n    metadata{\n      lqip,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n}\n  }\n': SERVICE_CATEGORIES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
